//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManachITDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public int PRODUCTOID { get; set; }
        public string DESCRIPCION { get; set; }
        public string NOMBRE { get; set; }
    }
}
